In [3]:
import pandas as pd 
import json

df1 = pd.read_csv('mturk_results/Batch_5356502_batch_results.csv', encoding='utf-8')
df2 = pd.read_csv('mturk_results/Batch_5356519_batch_results.csv', encoding='utf-8')

# merge the two dataframes
df = pd.concat([df1, df2], ignore_index=True)
df.columns

Index(['HITId', 'HITTypeId', 'Title', 'Description', 'Keywords', 'Reward',
       'CreationTime', 'MaxAssignments', 'RequesterAnnotation',
       'AssignmentDurationInSeconds', 'AutoApprovalDelayInSeconds',
       'Expiration', 'NumberOfSimilarHITs', 'LifetimeInSeconds',
       'AssignmentId', 'WorkerId', 'AssignmentStatus', 'AcceptTime',
       'SubmitTime', 'AutoApprovalTime', 'ApprovalTime', 'RejectionTime',
       'RequesterFeedback', 'WorkTimeInSeconds', 'LifetimeApprovalRate',
       'Last30DaysApprovalRate', 'Last7DaysApprovalRate', 'Input.q_strings',
       'Answer.taskAnswers', 'Approve', 'Reject'],
      dtype='object')

In [4]:
submission_df = df[['WorkerId','WorkTimeInSeconds','Answer.taskAnswers']]
submission_df

,WorkerId,WorkTimeInSeconds,Answer.taskAnswers
0,A2H3SVUWH2L9ZO,981,"[{""104_B_ours_ar_q1"":{""ar"":false,""ours"":true},..."
1,A2N94XU62FQKB9,1207,"[{""074_B_ours_lam_q1"":{""lam"":false,""ours"":true..."
2,A2OXGAYFXOIVYS,679,"[{""074_A_ar_ours_q1"":{""ar"":false,""ours"":true},..."
3,A2UR7QQI8FBLE0,183,"[{""074_A_ours_hr_q1"":{""hr"":false,""ours"":true},..."
4,A1RWHQIX1934RI,1274,"[{""074_B_ours_4dgs_q1"":{""4dgs"":false,""ours"":tr..."
...,...,...,...
115,ADSEGF47JPK5L,374,"[{""074_A_lam_ours_q1"":{""lam"":false,""ours"":true..."
116,A19BQKCS0MF3A5,1391,"[{""104_B_gaga_ours_q1"":{""gaga"":false,""ours"":tr..."
117,A35J9IIFZC67I2,509,"[{""104_A_ar_ours_q1"":{""ar"":true,""ours"":false},..."
118,A1TK7V460ZKPYT,563,"[{""074_B_lam_ours_q1"":{""lam"":false,""ours"":true..."
119,A26JZCXT4WWHNU,1148,"[{""074_A_ar_ours_q1"":{""ar"":false,""ours"":true},..."

In [6]:
# answer stats per worker
# recall: each worker answers 9 x 3 = 27 questions, full score is 27
for i in range(len(submission_df)):
    print(f"workerid: {submission_df.at[i, 'WorkerId']}, worktime: {submission_df.at[i, 'WorkTimeInSeconds']}")
    answer_json = json.loads(submission_df.at[i, 'Answer.taskAnswers'])
    methods = ['ours', 'ga', 'ar', '4dgs', 'lam', 'gaga', 'hr']
    score_dict = {method: 0 for method in methods}
    for question, answer in answer_json[0].items():
        # print(f"question: {question}, answer: {answer}") # see individual answers
        for method, score in answer.items():
            if method in methods:
                score_dict[method] += int(score)
    print(f"score_dict: {score_dict}")

workerid: A2H3SVUWH2L9ZO, worktime: 981
score_dict: {'ours': 16, 'ga': 2, 'ar': 1, '4dgs': 5, 'lam': 3, 'gaga': 0, 'hr': 0}
workerid: A2N94XU62FQKB9, worktime: 1207
score_dict: {'ours': 24, 'ga': 0, 'ar': 0, '4dgs': 3, 'lam': 0, 'gaga': 0, 'hr': 0}
workerid: A2OXGAYFXOIVYS, worktime: 679
score_dict: {'ours': 21, 'ga': 2, 'ar': 0, '4dgs': 0, 'lam': 0, 'gaga': 3, 'hr': 1}
workerid: A2UR7QQI8FBLE0, worktime: 183
score_dict: {'ours': 21, 'ga': 0, 'ar': 0, '4dgs': 3, 'lam': 0, 'gaga': 3, 'hr': 0}
workerid: A1RWHQIX1934RI, worktime: 1274
score_dict: {'ours': 17, 'ga': 3, 'ar': 1, '4dgs': 3, 'lam': 1, 'gaga': 0, 'hr': 2}
workerid: A3QTSAB6UOBSKM, worktime: 284
score_dict: {'ours': 21, 'ga': 3, 'ar': 0, '4dgs': 0, 'lam': 3, 'gaga': 0, 'hr': 0}
workerid: A2X9J2CBD5D5TU, worktime: 410
score_dict: {'ours': 21, 'ga': 0, 'ar': 5, '4dgs': 1, 'lam': 0, 'gaga': 0, 'hr': 0}
workerid: AUEJL4P5KPSXL, worktime: 1150
score_dict: {'ours': 16, 'ga': 3, 'ar': 1, '4dgs': 3, 'lam': 1, 'gaga': 3, 'hr': 0}
workerid: A1DOHBEHS0UY9B, worktime: 724
score_dict: {'ours': 27, 'ga': 0, 'ar': 0, '4dgs': 0, 'lam': 0, 'gaga': 0, 'hr': 0}
workerid: A4W6VB5YF176F, worktime: 1328
score_dict: {'ours': 25, 'ga': 0, 'ar': 0, '4dgs': 0, 'lam': 0, 'gaga': 2, 'hr': 0}
workerid: A2GHBW589BTASK, worktime: 1499
score_dict: {'ours': 17, 'ga': 3, 'ar': 3, '4dgs': 1, 'lam': 0, 'gaga': 1, 'hr': 2}
workerid: A3GH9VBM0SQYJ1, worktime: 690
score_dict: {'ours': 26, 'ga': 0, 'ar': 1, '4dgs': 0, 'lam': 0, 'gaga': 0, 'hr': 0}
workerid: A1VAM3KKZHIGC7, worktime: 477
score_dict: {'ours': 24, 'ga': 0, 'ar': 3, '4dgs': 0, 'lam': 0, 'gaga': 0, 'hr': 0}
workerid: A2QV1IXSCG0XW1, worktime: 845
score_dict: {'ours': 18, 'ga': 2, 'ar': 2, '4dgs': 3, 'lam': 0, 'gaga': 1, 'hr': 1}
workerid: A1RZYFWFP9M2ZL, worktime: 302
score_dict: {'ours': 27, 'ga': 0, 'ar': 0, '4dgs': 0, 'lam': 0, 'gaga': 0, 'hr': 0}
workerid: AD2XPS2WCTVTY, worktime: 1266
score_dict: {'ours': 21, 'ga': 0, 'ar': 0, '4dgs': 0, 'lam': 0, 'gaga': 6, 'hr': 0}
workerid: A1N39CN0X2GKX3, worktime: 1273
score_dict: {'ours': 27, 'ga': 0, 'ar': 0, '4dgs': 0, 'lam': 0, 'gaga': 0, 'hr': 0}
workerid: A1QFPWH5R4ASUU, worktime: 970
score_dict: {'ours': 27, 'ga': 0, 'ar': 0, '4dgs': 0, 'lam': 0, 'gaga': 0, 'hr': 0}
workerid: AO3KV1IZ26U6V, worktime: 768
score_dict: {'ours': 27, 'ga': 0, 'ar': 0, '4dgs': 0, 'lam': 0, 'gaga': 0, 'hr': 0}
workerid: AWB5O2CA6XQ3X, worktime: 982
score_dict: {'ours': 22, 'ga': 1, 'ar': 2, '4dgs': 1, 'lam': 0, 'gaga': 1, 'hr': 0}
workerid: A24Z7AVA07LHT4, worktime: 515
score_dict: {'ours': 15, 'ga': 0, 'ar': 4, '4dgs': 0, 'lam': 3, 'gaga': 4, 'hr': 1}
workerid: AJLTEMUMRBWDU, worktime: 487
score_dict: {'ours': 25, 'ga': 0, 'ar': 0, '4dgs': 0, 'lam': 0, 'gaga': 2, 'hr': 0}
workerid: A2OMN0ACWUUX1T, worktime: 573
score_dict: {'ours': 27, 'ga': 0, 'ar': 0, '4dgs': 0, 'lam': 0, 'gaga': 0, 'hr': 0}
workerid: A4A66G10CLVDX, worktime: 823
score_dict: {'ours': 13, 'ga': 2, 'ar': 3, '4dgs': 2, 'lam': 1, 'gaga': 3, 'hr': 3}
workerid: AL84FSIS4UM1Q, worktime: 1721
score_dict: {'ours': 25, 'ga': 2, 'ar': 0, '4dgs': 0, 'lam': 0, 'gaga': 0, 'hr': 0}
workerid: A1SDR3JAF2D9J5, worktime: 1670
score_dict: {'ours': 27, 'ga': 0, 'ar': 0, '4dgs': 0, 'lam': 0, 'gaga': 0, 'hr': 0}
workerid: A3NGH4FZIL5LA4, worktime: 1335
score_dict: {'ours': 27, 'ga': 0, 'ar': 0, '4dgs': 0, 'lam': 0, 'gaga': 0, 'hr': 0}
workerid: A2HIT6GAB0NBGE, worktime: 815
score_dict: {'ours': 13, 'ga': 3, 'ar': 3, '4dgs': 2, 'lam': 3, 'gaga': 1, 'hr': 2}
workerid: A1DI8ZA02L9GMS, worktime: 1366
score_dict: {'ours': 16, 'ga': 1, 'ar': 1, '4dgs': 1, 'lam': 3, 'gaga': 3, 'hr': 2}
workerid: ACBN651UJTV9K, worktime: 486
score_dict: {'ours': 15, 'ga': 8, 'ar': 1, '4dgs': 0, 'lam': 0, 'gaga': 0, 'hr': 3}
workerid: A1XN76VXDDX7PB, worktime: 631
score_dict: {'ours': 26, 'ga': 1, 'ar': 0, '4dgs': 0, 'lam': 0, 'gaga': 0, 'hr': 0}
workerid: A2UD7BGX6IKF35, worktime: 906
score_dict: {'ours': 20, 'ga': 0, 'ar': 1, '4dgs': 1, 'lam': 1, 'gaga': 2, 'hr': 2}
workerid: A1391Q0GNLGNAH, worktime: 323
score_dict: {'ours': 27, 'ga': 0, 'ar': 0, '4dgs': 0, 'lam': 0, 'gaga': 0, 'hr': 0}
workerid: A37T2KVVFWLKGY, worktime: 938
score_dict: {'ours': 18, 'ga': 3, 'ar': 2, '4dgs': 1, 'lam': 1, 'gaga': 0, 'hr': 2}
workerid: A2OL2H6XXJDFMD, worktime: 1206
score_dict: {'ours': 27, 'ga': 0, 'ar': 0, '4dgs': 0, 'lam': 0, 'gaga': 0, 'hr': 0}
workerid: A3EABTUC3IGT6R, worktime: 1278
score_dict: {'ours': 24, 'ga': 3, 'ar': 0, '4dgs': 0, 'lam': 0, 'gaga': 0, 'hr': 0}
workerid: A31GCQCU3AZFF0, worktime: 523
score_dict: {'ours': 17, 'ga': 0, 'ar': 1, '4dgs': 4, 'lam': 4, 'gaga': 0, 'hr': 1}
workerid: ALVZZ451YC17N, worktime: 309
score_dict: {'ours': 27, 'ga': 0, 'ar': 0, '4dgs': 0, 'lam': 0, 'gaga': 0, 'hr': 0}
workerid: A23KPIMDQ7N4P9, worktime: 1263
score_dict: {'ours': 24, 'ga': 2, 'ar': 0, '4dgs': 1, 'lam': 0, 'gaga': 0, 'hr': 0}
workerid: A2Z7KI9N4EMF2N, worktime: 959
score_dict: {'ours': 17, 'ga': 3, 'ar': 1, '4dgs': 2, 'lam': 0, 'gaga': 4, 'hr': 0}
workerid: AACSV55WVN0JO, worktime: 329
score_dict: {'ours': 18, 'ga': 2, 'ar': 1, '4dgs': 2, 'lam': 0, 'gaga': 2, 'hr': 2}
workerid: A252P021BXZ764, worktime: 802
score_dict: {'ours': 20, 'ga': 0, 'ar': 4, '4dgs': 1, 'lam': 1, 'gaga': 0, 'hr': 1}
workerid: AFO2L3H7S90XY, worktime: 689
score_dict: {'ours': 14, 'ga': 3, 'ar': 0, '4dgs': 2, 'lam': 2, 'gaga': 5, 'hr': 1}
workerid: A31EV3B5YDKMY5, worktime: 1562
score_dict: {'ours': 27, 'ga': 0, 'ar': 0, '4dgs': 0, 'lam': 0, 'gaga': 0, 'hr': 0}
workerid: A1BH26DT1UA88B, worktime: 1424
score_dict: {'ours': 18, 'ga': 2, 'ar': 2, '4dgs': 1, 'lam': 2, 'gaga': 0, 'hr': 2}
workerid: A30QA03J5XUNQP, worktime: 1719
score_dict: {'ours': 11, 'ga': 1, 'ar': 7, '4dgs': 1, 'lam': 2, 'gaga': 4, 'hr': 1}
workerid: A1WZZUYLBJ8W9P, worktime: 298
score_dict: {'ours': 27, 'ga': 0, 'ar': 0, '4dgs': 0, 'lam': 0, 'gaga': 0, 'hr': 0}
workerid: AI64XV1HXJU3R, worktime: 674
score_dict: {'ours': 27, 'ga': 0, 'ar': 0, '4dgs': 0, 'lam': 0, 'gaga': 0, 'hr': 0}
workerid: ALT9RPC09YP64, worktime: 867
score_dict: {'ours': 11, 'ga': 2, 'ar': 3, '4dgs': 3, 'lam': 2, 'gaga': 6, 'hr': 0}
workerid: A3QTSAB6UOBSKM, worktime: 1560
score_dict: {'ours': 12, 'ga': 4, 'ar': 6, '4dgs': 3, 'lam': 0, 'gaga': 0, 'hr': 2}
workerid: A2NN9UR74KZKC, worktime: 377
score_dict: {'ours': 20, 'ga': 0, 'ar': 2, '4dgs': 1, 'lam': 1, 'gaga': 3, 'hr': 0}
workerid: A7H4ERH88PYF, worktime: 400
score_dict: {'ours': 27, 'ga': 0, 'ar': 0, '4dgs': 0, 'lam': 0, 'gaga': 0, 'hr': 0}
workerid: A2OXE4RAPC1HFL, worktime: 614
score_dict: {'ours': 18, 'ga': 0, 'ar': 1, '4dgs': 1, 'lam': 2, 'gaga': 2, 'hr': 3}
workerid: A1IN9OCE273FEN, worktime: 755
score_dict: {'ours': 15, 'ga': 3, 'ar': 1, '4dgs': 0, 'lam': 3, 'gaga': 3, 'hr': 2}
workerid: A3999XE418RQ3X, worktime: 979
score_dict: {'ours': 22, 'ga': 1, 'ar': 2, '4dgs': 0, 'lam': 0, 'gaga': 2, 'hr': 0}
workerid: A2LOJYNHNGIOZQ, worktime: 134
score_dict: {'ours': 17, 'ga': 0, 'ar': 1, '4dgs': 3, 'lam': 1, 'gaga': 0, 'hr': 5}
workerid: AGVZ6H8KOQJ7L, worktime: 664
score_dict: {'ours': 26, 'ga': 0, 'ar': 1, '4dgs': 0, 'lam': 0, 'gaga': 0, 'hr': 0}
workerid: APXK08LMHFHM8, worktime: 824
score_dict: {'ours': 25, 'ga': 0, 'ar': 1, '4dgs': 0, 'lam': 0, 'gaga': 1, 'hr': 0}
workerid: A3J6BV8BILD416, worktime: 869
score_dict: {'ours': 13, 'ga': 0, 'ar': 0, '4dgs': 5, 'lam': 5, 'gaga': 3, 'hr': 1}
workerid: A19W6MXLGRKCDA, worktime: 675
score_dict: {'ours': 14, 'ga': 0, 'ar': 2, '4dgs': 3, 'lam': 0, 'gaga': 2, 'hr': 6}
workerid: A3CCZSHRCIV3F3, worktime: 1267
score_dict: {'ours': 13, 'ga': 6, 'ar': 1, '4dgs': 1, 'lam': 0, 'gaga': 3, 'hr': 3}
workerid: AQ29XB1EZ954V, worktime: 876
score_dict: {'ours': 13, 'ga': 1, 'ar': 3, '4dgs': 0, 'lam': 1, 'gaga': 3, 'hr': 6}
workerid: A37HUVGB6ZT2ET, worktime: 1539
score_dict: {'ours': 12, 'ga': 2, 'ar': 0, '4dgs': 0, 'lam': 1, 'gaga': 6, 'hr': 6}
workerid: A145C8GKNAG28E, worktime: 441
score_dict: {'ours': 27, 'ga': 0, 'ar': 0, '4dgs': 0, 'lam': 0, 'gaga': 0, 'hr': 0}
workerid: A3BXMUM6C6TK23, worktime: 1607
score_dict: {'ours': 27, 'ga': 0, 'ar': 0, '4dgs': 0, 'lam': 0, 'gaga': 0, 'hr': 0}
workerid: ANQI9P5RCFGFL, worktime: 579
score_dict: {'ours': 27, 'ga': 0, 'ar': 0, '4dgs': 0, 'lam': 0, 'gaga': 0, 'hr': 0}
workerid: A3DDLB77MTSBHC, worktime: 1456
score_dict: {'ours': 27, 'ga': 0, 'ar': 0, '4dgs': 0, 'lam': 0, 'gaga': 0, 'hr': 0}
workerid: A1391Q0GNLGNAH, worktime: 525
score_dict: {'ours': 27, 'ga': 0, 'ar': 0, '4dgs': 0, 'lam': 0, 'gaga': 0, 'hr': 0}
workerid: A3JEU47OJ0JDK3, worktime: 433
score_dict: {'ours': 21, 'ga': 3, 'ar': 3, '4dgs': 0, 'lam': 0, 'gaga': 0, 'hr': 0}
workerid: A3TWUHIMBPP5QZ, worktime: 1722
score_dict: {'ours': 27, 'ga': 0, 'ar': 0, '4dgs': 0, 'lam': 0, 'gaga': 0, 'hr': 0}
workerid: A1O6Y3RZT838LI, worktime: 1275
score_dict: {'ours': 27, 'ga': 0, 'ar': 0, '4dgs': 0, 'lam': 0, 'gaga': 0, 'hr': 0}
workerid: AD59Z15DC5TT2, worktime: 425
score_dict: {'ours': 25, 'ga': 0, 'ar': 0, '4dgs': 0, 'lam': 0, 'gaga': 0, 'hr': 2}
workerid: A1E52LFSP00Y8R, worktime: 134
score_dict: {'ours': 21, 'ga': 4, 'ar': 0, '4dgs': 0, 'lam': 0, 'gaga': 2, 'hr': 0}
workerid: A3QTO07BNMNJ8O, worktime: 1111
score_dict: {'ours': 24, 'ga': 3, 'ar': 0, '4dgs': 0, 'lam': 0, 'gaga': 0, 'hr': 0}
workerid: AEJDWF3GUM7SU, worktime: 528
score_dict: {'ours': 17, 'ga': 2, 'ar': 3, '4dgs': 1, 'lam': 2, 'gaga': 0, 'hr': 2}
workerid: A2P7AZ8ZGP5I7G, worktime: 723
score_dict: {'ours': 27, 'ga': 0, 'ar': 0, '4dgs': 0, 'lam': 0, 'gaga': 0, 'hr': 0}
workerid: A1LMVWFAKO46A1, worktime: 699
score_dict: {'ours': 15, 'ga': 3, 'ar': 4, '4dgs': 0, 'lam': 0, 'gaga': 3, 'hr': 2}
workerid: AFTGUFK7FG57O, worktime: 870
score_dict: {'ours': 16, 'ga': 2, 'ar': 0, '4dgs': 1, 'lam': 2, 'gaga': 5, 'hr': 1}
workerid: A2OOHVZPVI4IPK, worktime: 931
score_dict: {'ours': 13, 'ga': 2, 'ar': 2, '4dgs': 2, 'lam': 5, 'gaga': 3, 'hr': 0}
workerid: A1HPEY1GDOLK3R, worktime: 1028
score_dict: {'ours': 27, 'ga': 0, 'ar': 0, '4dgs': 0, 'lam': 0, 'gaga': 0, 'hr': 0}
workerid: A9LAADN925ZUR, worktime: 648
score_dict: {'ours': 27, 'ga': 0, 'ar': 0, '4dgs': 0, 'lam': 0, 'gaga': 0, 'hr': 0}
workerid: A39J72BBHMWBBY, worktime: 1471
score_dict: {'ours': 27, 'ga': 0, 'ar': 0, '4dgs': 0, 'lam': 0, 'gaga': 0, 'hr': 0}
workerid: ABQ2YPX1MB6JW, worktime: 228
score_dict: {'ours': 24, 'ga': 3, 'ar': 0, '4dgs': 0, 'lam': 0, 'gaga': 0, 'hr': 0}
workerid: A18WDR1RQHEQ7D, worktime: 427
score_dict: {'ours': 15, 'ga': 5, 'ar': 0, '4dgs': 4, 'lam': 0, 'gaga': 1, 'hr': 2}
workerid: APHVEP5RZ9XHH, worktime: 759
score_dict: {'ours': 24, 'ga': 3, 'ar': 0, '4dgs': 0, 'lam': 0, 'gaga': 0, 'hr': 0}
workerid: A3QZF1RGS7ANSD, worktime: 1302
score_dict: {'ours': 25, 'ga': 0, 'ar': 0, '4dgs': 0, 'lam': 0, 'gaga': 1, 'hr': 1}
workerid: APWRD98O6FG5K, worktime: 1743
score_dict: {'ours': 27, 'ga': 0, 'ar': 0, '4dgs': 0, 'lam': 0, 'gaga': 0, 'hr': 0}
workerid: A343GQXQ1ZGGBZ, worktime: 1158
score_dict: {'ours': 27, 'ga': 0, 'ar': 0, '4dgs': 0, 'lam': 0, 'gaga': 0, 'hr': 0}
workerid: A383H58QWPQFMA, worktime: 364
score_dict: {'ours': 17, 'ga': 0, 'ar': 0, '4dgs': 4, 'lam': 2, 'gaga': 0, 'hr': 4}
workerid: ACEG8AQ5O82ZY, worktime: 685
score_dict: {'ours': 24, 'ga': 3, 'ar': 0, '4dgs': 0, 'lam': 0, 'gaga': 0, 'hr': 0}
workerid: A3IX9MV2SX545Z, worktime: 686
score_dict: {'ours': 27, 'ga': 0, 'ar': 0, '4dgs': 0, 'lam': 0, 'gaga': 0, 'hr': 0}
workerid: A315N5OOKFOREL, worktime: 223
score_dict: {'ours': 21, 'ga': 0, 'ar': 0, '4dgs': 0, 'lam': 0, 'gaga': 6, 'hr': 0}
workerid: A2IVS85THONGOU, worktime: 797
score_dict: {'ours': 22, 'ga': 0, 'ar': 3, '4dgs': 1, 'lam': 0, 'gaga': 1, 'hr': 0}
workerid: A2EOCWIL2OHNJ, worktime: 1393
score_dict: {'ours': 27, 'ga': 0, 'ar': 0, '4dgs': 0, 'lam': 0, 'gaga': 0, 'hr': 0}
workerid: A37HUVGB6ZT2ET, worktime: 915
score_dict: {'ours': 12, 'ga': 0, 'ar': 3, '4dgs': 4, 'lam': 0, 'gaga': 5, 'hr': 3}
workerid: ABVA5HP8ACO5Q, worktime: 1068
score_dict: {'ours': 24, 'ga': 0, 'ar': 3, '4dgs': 0, 'lam': 0, 'gaga': 0, 'hr': 0}
workerid: A1RP7H6KLEB2D6, worktime: 1277
score_dict: {'ours': 18, 'ga': 0, 'ar': 2, '4dgs': 0, 'lam': 2, 'gaga': 1, 'hr': 4}
workerid: A3040JXG7HF4A5, worktime: 293
score_dict: {'ours': 14, 'ga': 7, 'ar': 1, '4dgs': 0, 'lam': 2, 'gaga': 2, 'hr': 1}
workerid: ANHWX99RNY3TE, worktime: 1019
score_dict: {'ours': 27, 'ga': 0, 'ar': 0, '4dgs': 0, 'lam': 0, 'gaga': 0, 'hr': 0}
workerid: A2VRGX567ZC4P1, worktime: 418
score_dict: {'ours': 27, 'ga': 0, 'ar': 0, '4dgs': 0, 'lam': 0, 'gaga': 0, 'hr': 0}
workerid: A32LNHNA9OKEP3, worktime: 1120
score_dict: {'ours': 24, 'ga': 0, 'ar': 0, '4dgs': 3, 'lam': 0, 'gaga': 0, 'hr': 0}
workerid: ALP1DCNK88BDY, worktime: 719
score_dict: {'ours': 17, 'ga': 0, 'ar': 7, '4dgs': 3, 'lam': 0, 'gaga': 0, 'hr': 0}
workerid: A1KLLYT0ITXDK4, worktime: 1221
score_dict: {'ours': 24, 'ga': 0, 'ar': 3, '4dgs': 0, 'lam': 0, 'gaga': 0, 'hr': 0}
workerid: A3J1WLKKLL52FO, worktime: 1715
score_dict: {'ours': 21, 'ga': 2, 'ar': 2, '4dgs': 2, 'lam': 0, 'gaga': 0, 'hr': 0}
workerid: A1UZ8W0UD3D28N, worktime: 495
score_dict: {'ours': 13, 'ga': 4, 'ar': 0, '4dgs': 0, 'lam': 2, 'gaga': 7, 'hr': 1}
workerid: A38AQHNQOOPGY4, worktime: 1048
score_dict: {'ours': 24, 'ga': 0, 'ar': 0, '4dgs': 0, 'lam': 0, 'gaga': 3, 'hr': 0}
workerid: A3SWFTF2Z4JY0L, worktime: 1119
score_dict: {'ours': 11, 'ga': 3, 'ar': 3, '4dgs': 3, 'lam': 3, 'gaga': 3, 'hr': 1}
workerid: A26474IH4VINI, worktime: 605
score_dict: {'ours': 27, 'ga': 0, 'ar': 0, '4dgs': 0, 'lam': 0, 'gaga': 0, 'hr': 0}
workerid: A37ZCFDIQ3II3J, worktime: 466
score_dict: {'ours': 27, 'ga': 0, 'ar': 0, '4dgs': 0, 'lam': 0, 'gaga': 0, 'hr': 0}
workerid: A2R3ZBYHB32AUY, worktime: 1007
score_dict: {'ours': 27, 'ga': 0, 'ar': 0, '4dgs': 0, 'lam': 0, 'gaga': 0, 'hr': 0}
workerid: A383H58QWPQFMA, worktime: 291
score_dict: {'ours': 19, 'ga': 0, 'ar': 2, '4dgs': 0, 'lam': 0, 'gaga': 0, 'hr': 6}
workerid: AUD9XPEM59ML1, worktime: 358
score_dict: {'ours': 17, 'ga': 0, 'ar': 3, '4dgs': 1, 'lam': 0, 'gaga': 3, 'hr': 3}
workerid: A1MO7MJBQDSUMH, worktime: 1723
score_dict: {'ours': 27, 'ga': 0, 'ar': 0, '4dgs': 0, 'lam': 0, 'gaga': 0, 'hr': 0}
workerid: A84VWIE13TZI0, worktime: 1636
score_dict: {'ours': 27, 'ga': 0, 'ar': 0, '4dgs': 0, 'lam': 0, 'gaga': 0, 'hr': 0}
workerid: A2FN1VXNQH3J8F, worktime: 456
score_dict: {'ours': 16, 'ga': 0, 'ar': 3, '4dgs': 2, 'lam': 0, 'gaga': 3, 'hr': 3}
workerid: ADSEGF47JPK5L, worktime: 374
score_dict: {'ours': 20, 'ga': 3, 'ar': 1, '4dgs': 2, 'lam': 0, 'gaga': 1, 'hr': 0}
workerid: A19BQKCS0MF3A5, worktime: 1391
score_dict: {'ours': 27, 'ga': 0, 'ar': 0, '4dgs': 0, 'lam': 0, 'gaga': 0, 'hr': 0}
workerid: A35J9IIFZC67I2, worktime: 509
score_dict: {'ours': 13, 'ga': 5, 'ar': 3, '4dgs': 0, 'lam': 2, 'gaga': 2, 'hr': 2}
workerid: A1TK7V460ZKPYT, worktime: 563
score_dict: {'ours': 21, 'ga': 2, 'ar': 0, '4dgs': 1, 'lam': 0, 'gaga': 1, 'hr': 2}
workerid: A26JZCXT4WWHNU, worktime: 1148
score_dict: {'ours': 27, 'ga': 0, 'ar': 0, '4dgs': 0, 'lam': 0, 'gaga': 0, 'hr': 0}

In [7]:
# method score distribution by subj+A/B

# create df (workerid, worktime, subj, speech, methodA, methodB, methodA_wins, methodB_wins, ours_wins, ga_wins, ar_wins, 4dgs_wins, lam_wins, gaga_wins, hr_wins)
df_list = []
for i in range(len(submission_df)):
    workerId = submission_df.at[i, 'WorkerId']
    worktime = submission_df.at[i, 'WorkTimeInSeconds']

    answer_json = json.loads(submission_df.at[i, 'Answer.taskAnswers'])
    methods = ['ours', 'ga', 'ar', '4dgs', 'lam', 'gaga', 'hr']
    # score_dict = {method: 0 for method in methods}
    for question, answer in answer_json[0].items():
        subj = question.split('_')[0]
        speech = question.split('_')[1]
        methodA = question.split('_')[2]
        methodB = question.split('_')[3]
        question_id = question.split('_')[4]

        methodA_wins = answer[methodA]
        methodB_wins = answer[methodB]

        # using wins, get 0,1,0,0,0,0,0 for ours, ga, ar, 4dgs, lam, gaga, hr
        ours_wins = 0
        ga_wins = 0
        ar_wins = 0
        dgs4_wins = 0
        lam_wins = 0
        gaga_wins = 0
        hr_wins = 0
        
        if methodA == 'ours':
            ours_wins = int(methodA_wins)
        elif methodA == 'ga':
            ga_wins = int(methodA_wins)
        elif methodA == 'ar':
            ar_wins = int(methodA_wins)
        elif methodA == '4dgs':
            dgs4_wins = int(methodA_wins)
        elif methodA == 'lam':
            lam_wins = int(methodA_wins)
        elif methodA == 'gaga':
            gaga_wins = int(methodA_wins)
        elif methodA == 'hr':
            hr_wins = int(methodA_wins)
        
        if methodB == 'ours':
            ours_wins = int(methodB_wins)
        elif methodB == 'ga':
            ga_wins = int(methodB_wins)
        elif methodB == 'ar':
            ar_wins = int(methodB_wins)
        elif methodB == '4dgs':
            dgs4_wins = int(methodB_wins)
        elif methodB == 'lam':
            lam_wins = int(methodB_wins)
        elif methodB == 'gaga':
            gaga_wins = int(methodB_wins)
        elif methodB == 'hr':
            hr_wins = int(methodB_wins)

        # create tuple
        df_list.append((workerId, worktime, subj, speech, question_id, methodA, methodB, methodA_wins, methodB_wins, ours_wins, ga_wins, ar_wins, dgs4_wins, lam_wins, gaga_wins, hr_wins))

# create df
df = pd.DataFrame(df_list, columns=['WorkerId', 'WorkTimeInSeconds', 'subj', 'speech', 'q_id', 'methodA', 'methodB', 'methodA_wins', 'methodB_wins', 'ours_wins', 'ga_wins', 'ar_wins', '4dgs_wins', 'lam_wins', 'gaga_wins', 'hr_wins'])
df

,WorkerId,WorkTimeInSeconds,subj,speech,q_id,methodA,methodB,methodA_wins,methodB_wins,ours_wins,ga_wins,ar_wins,4dgs_wins,lam_wins,gaga_wins,hr_wins
0,A2H3SVUWH2L9ZO,981,104,B,q1,ours,ar,True,False,1,0,0,0,0,0,0
1,A2H3SVUWH2L9ZO,981,104,B,q2,ours,ar,False,True,0,0,1,0,0,0,0
2,A2H3SVUWH2L9ZO,981,104,B,q3,ours,ar,True,False,1,0,0,0,0,0,0
3,A2H3SVUWH2L9ZO,981,218,A,q1,ga,ours,True,False,0,1,0,0,0,0,0
4,A2H3SVUWH2L9ZO,981,218,A,q2,ga,ours,False,True,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3235,A26JZCXT4WWHNU,1148,306,A,q2,ours,4dgs,True,False,1,0,0,0,0,0,0
3236,A26JZCXT4WWHNU,1148,306,A,q3,ours,4dgs,True,False,1,0,0,0,0,0,0
3237,A26JZCXT4WWHNU,1148,460,B,q1,ours,ar,True,False,1,0,0,0,0,0,0
3238,A26JZCXT4WWHNU,1148,460,B,q2,ours,ar,True,False,1,0,0,0,0,0,0
3239,A26JZCXT4WWHNU,1148,460,B,q3,ours,ar,True,False,1,0,0,0,0,0,0

In [8]:
df_binary = df.drop(columns=['methodA_wins', 'methodB_wins', 'methodA', 'methodB'])
df_binary

,WorkerId,WorkTimeInSeconds,subj,speech,q_id,ours_wins,ga_wins,ar_wins,4dgs_wins,lam_wins,gaga_wins,hr_wins
0,A2H3SVUWH2L9ZO,981,104,B,q1,1,0,0,0,0,0,0
1,A2H3SVUWH2L9ZO,981,104,B,q2,0,0,1,0,0,0,0
2,A2H3SVUWH2L9ZO,981,104,B,q3,1,0,0,0,0,0,0
3,A2H3SVUWH2L9ZO,981,218,A,q1,0,1,0,0,0,0,0
4,A2H3SVUWH2L9ZO,981,218,A,q2,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
3235,A26JZCXT4WWHNU,1148,306,A,q2,1,0,0,0,0,0,0
3236,A26JZCXT4WWHNU,1148,306,A,q3,1,0,0,0,0,0,0
3237,A26JZCXT4WWHNU,1148,460,B,q1,1,0,0,0,0,0,0
3238,A26JZCXT4WWHNU,1148,460,B,q2,1,0,0,0,0,0,0
3239,A26JZCXT4WWHNU,1148,460,B,q3,1,0,0,0,0,0,0

In [9]:
df_binary['WorkTimeInSeconds'].describe()

count    3240.000000
mean      872.008333
std       432.818449
min       134.000000
25%       505.500000
50%       819.000000
75%      1231.500000
max      1743.000000
Name: WorkTimeInSeconds, dtype: float64

In [10]:
df_binary.groupby(['WorkerId','WorkTimeInSeconds']).sum(['ours_wins', 'ga_wins', 'ar_wins', '4dgs_wins', 'lam_wins', 'gaga_wins', 'hr_wins']).reset_index()

,WorkerId,WorkTimeInSeconds,ours_wins,ga_wins,ar_wins,4dgs_wins,lam_wins,gaga_wins,hr_wins
0,A1391Q0GNLGNAH,323,27,0,0,0,0,0,0
1,A1391Q0GNLGNAH,525,27,0,0,0,0,0,0
2,A145C8GKNAG28E,441,27,0,0,0,0,0,0
3,A18WDR1RQHEQ7D,427,15,5,0,4,0,1,2
4,A19BQKCS0MF3A5,1391,27,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...
115,APXK08LMHFHM8,824,25,0,1,0,0,1,0
116,AQ29XB1EZ954V,876,13,1,3,0,1,3,6
117,AUD9XPEM59ML1,358,17,0,3,1,0,3,3
118,AUEJL4P5KPSXL,1150,16,3,1,3,1,3,0
119,AWB5O2CA6XQ3X,982,22,1,2,1,0,1,0

In [ ]:
# Q: what subject+AB did ours lose the most?
df_binary.drop(columns=['WorkTimeInSeconds']).groupby(['subj','speech']).sum(['ours_wins', 'ga_wins', 'ar_wins', '4dgs_wins', 'lam_wins', 'gaga_wins', 'hr_wins']).reset_index()

   subj speech  ours_wins  ga_wins  talkg_wins  instag_wins
0   074      A        129       14          15           22
1   074      B        149        8           8           15
2   104      A        112       20          26           22
3   104      B        120       14          23           23
4   218      A        119       13          28           20
5   218      B        136        3          22           19
6   253      A        137       16          12           15
7   253      B        110       11          38           21
8   264      A         94       23          34           29
9   264      B        126       13          23           18
10  302      A        109       14          30           27
11  302      B        117        9          30           24
12  304      A        114       19          29           18
13  304      B        126       15          26           13
14  306      A        105       22          24           29
15  306      B        123       20          17           20
16  460      A        106       18          36           20
17  460      B        109       16          25           30

In [11]:
# Q: what question (1,2,3) did ours lose the most?
df_binary.drop(columns=['WorkTimeInSeconds']).groupby(['q_id']).sum(['ours_wins', 'ga_wins', 'ar_wins', '4dgs_wins', 'lam_wins', 'gaga_wins', 'hr_wins']).reset_index()

# finding: we win in realness, lip sync & quality debatable

  q_id  ours_wins  ga_wins  ar_wins  4dgs_wins  lam_wins  gaga_wins  hr_wins
0   q1        846       49       40         31        22         51       41
1   q2        839       46       44         34        30         46       41
2   q3        890       38       41         33        17         40       21

In [19]:
all_wins = df_binary.drop(columns=['WorkTimeInSeconds']).groupby(['q_id']).sum(['ours_wins', 'ga_wins', 'ar_wins', '4dgs_wins', 'lam_wins', 'gaga_wins', 'hr_wins']).reset_index()

all_wins = all_wins.drop(columns=['ours_wins'])
# divide all numbers in all_wins by 360
# 360 = 20 workers x 9 questions x 2 (A/B) for sigA
# 180 = 10 workers x 9 questions x 2 (A/B) for cvpr

num_participants_per_question = 10
num_subjects = 9
num_sentences = 2
num_comparisons_per_method = num_participants_per_question * num_subjects * num_sentences

all_wins['ours_wins_ga'] = 1 - all_wins['ga_wins'] / num_comparisons_per_method
all_wins['ours_wins_ar'] = 1 - all_wins['ar_wins'] / num_comparisons_per_method
all_wins['ours_wins_4dgs'] = 1 - all_wins['4dgs_wins'] / num_comparisons_per_method
all_wins['ours_wins_lam'] = 1 - all_wins['lam_wins'] / num_comparisons_per_method
all_wins['ours_wins_gaga'] = 1 - all_wins['gaga_wins'] / num_comparisons_per_method
all_wins['ours_wins_hr'] = 1 - all_wins['hr_wins'] / num_comparisons_per_method

all_wins

,q_id,ga_wins,ar_wins,4dgs_wins,lam_wins,gaga_wins,hr_wins,ours_wins_ga,ours_wins_ar,ours_wins_4dgs,ours_wins_lam,ours_wins_gaga,ours_wins_hr
0,q1,49,40,31,22,51,41,0.727778,0.777778,0.827778,0.877778,0.716667,0.772222
1,q2,46,44,34,30,46,41,0.744444,0.755556,0.811111,0.833333,0.744444,0.772222
2,q3,38,41,33,17,40,21,0.788889,0.772222,0.816667,0.905556,0.777778,0.883333

In [20]:
# flip the ours_wins to get ours_losses
all_wins['ours_losses_ga'] = 1 - all_wins['ours_wins_ga']
all_wins['ours_losses_ar'] = 1 - all_wins['ours_wins_ar']
all_wins['ours_losses_4dgs'] = 1 - all_wins['ours_wins_4dgs']
all_wins['ours_losses_lam'] = 1 - all_wins['ours_wins_lam']
all_wins['ours_losses_gaga'] = 1 - all_wins['ours_wins_gaga']
all_wins['ours_losses_hr'] = 1 - all_wins['ours_wins_hr']   
all_losses = all_wins.drop(columns=['ours_wins_ga', 'ours_wins_ar', 'ours_wins_4dgs', 'ours_wins_lam', 'ours_wins_gaga', 'ours_wins_hr'])
all_losses

,q_id,ga_wins,ar_wins,4dgs_wins,lam_wins,gaga_wins,hr_wins,ours_losses_ga,ours_losses_ar,ours_losses_4dgs,ours_losses_lam,ours_losses_gaga,ours_losses_hr
0,q1,49,40,31,22,51,41,0.272222,0.222222,0.172222,0.122222,0.283333,0.227778
1,q2,46,44,34,30,46,41,0.255556,0.244444,0.188889,0.166667,0.255556,0.227778
2,q3,38,41,33,17,40,21,0.211111,0.227778,0.183333,0.094444,0.222222,0.116667

In [22]:
# show ours_losses for each method in percentages
for method in ['ours_losses_ga', 'ours_losses_ar', 'ours_losses_4dgs', 'ours_losses_lam', 'ours_losses_gaga', 'ours_losses_hr']:
    all_losses[method] = all_losses[method] * 100
all_losses

,q_id,ga_wins,ar_wins,4dgs_wins,lam_wins,gaga_wins,hr_wins,ours_losses_ga,ours_losses_ar,ours_losses_4dgs,ours_losses_lam,ours_losses_gaga,ours_losses_hr
0,q1,49,40,31,22,51,41,27.222222,22.222222,17.222222,12.222222,28.333333,22.777778
1,q2,46,44,34,30,46,41,25.555556,24.444444,18.888889,16.666667,25.555556,22.777778
2,q3,38,41,33,17,40,21,21.111111,22.777778,18.333333,9.444444,22.222222,11.666667

In [21]:
# Q: what subject+AB+q did ours lose the most?
df_binary.drop(columns=['WorkTimeInSeconds']).groupby(['subj','speech','q_id']).sum(['ours_wins', 'ga_wins', 'ar_wins', '4dgs_wins', 'lam_wins', 'gaga_wins', 'hr_wins']).reset_index()

,subj,speech,q_id,ours_wins,ga_wins,ar_wins,4dgs_wins,lam_wins,gaga_wins,hr_wins
0,074,A,q1,49,1,1,2,1,3,3
1,074,A,q2,49,2,1,1,0,5,2
2,074,A,q3,53,2,2,2,0,0,1
3,074,B,q1,45,1,5,0,3,4,2
4,074,B,q2,45,2,4,2,1,5,1
5,074,B,q3,49,2,3,2,1,3,0
6,104,A,q1,45,1,4,2,0,4,4
7,104,A,q2,41,3,5,3,3,3,2
8,104,A,q3,53,0,3,3,0,0,1
9,104,B,q1,48,1,4,1,1,2,3
10,104,B,q2,50,0,2,3,0,2,3
11,104,B,q3,52,1,3,0,0,3,1
12,218,A,q1,40,7,2,2,1,5,3
13,218,A,q2,44,2,2,2,2,3,5
14,218,A,q3,46,5,2,1,0,5,1
15,218,B,q1,49,2,3,2,0,2,2
16,218,B,q2,50,2,1,2,1,2,2
17,218,B,q3,52,1,2,2,0,2,1
18,253,A,q1,49,4,2,2,0,1,2
19,253,A,q2,42,4,4,2,3,2,3
20,253,A,q3,52,2,2,1,2,0,1
21,253,B,q1,49,3,1,0,2,3,2
22,253,B,q2,51,2,3,0,2,1,1
23,253,B,q3,47,4,3,2,1,1,2
24,264,A,q1,50,2,0,2,1,2,3
25,264,A,q2,47,3,1,3,1,1,4
26,264,A,q3,54,2,0,2,0,2,0
27,264,B,q1,45,5,2,4,1,2,1
28,264,B,q2,49,5,2,1,2,0,1
29,264,B,q3,49,2,3,2,1,2,1
30,302,A,q1,49,4,1,1,2,1,2
31,302,A,q2,51,2,1,1,1,3,1
32,302,A,q3,47,3,0,2,2,3,3
33,302,B,q1,49,3,3,3,0,1,1
34,302,B,q2,45,4,4,2,1,4,0
35,302,B,q3,47,3,3,3,1,2,1
36,304,A,q1,47,2,1,2,2,5,1
37,304,A,q2,47,2,2,2,1,3,3
38,304,A,q3,53,2,2,2,0,1,0
39,304,B,q1,44,3,3,3,1,4,2
40,304,B,q2,46,2,3,1,3,3,2
41,304,B,q3,49,1,1,2,1,4,2
42,306,A,q1,49,3,2,2,1,3,0
43,306,A,q2,42,5,2,1,2,4,4
44,306,A,q3,49,3,3,0,1,3,1
45,306,B,q1,49,1,1,0,1,4,4
46,306,B,q2,47,1,2,3,3,0,4
47,306,B,q3,46,0,3,3,2,3,3
48,460,A,q1,45,3,4,2,1,3,2
49,460,A,q2,45,3,3,3,2,3,1
50,460,A,q3,47,3,4,3,1,2,0
51,460,B,q1,45,3,1,1,4,2,4
52,460,B,q2,48,2,2,2,2,2,2
53,460,B,q3,45,2,2,1,4,4,2

In [96]:
# sort by time
df_binary.sort_values(by=['WorkTimeInSeconds'], ascending=True, inplace=True)
df_binary

,WorkerId,WorkTimeInSeconds,subj,speech,q_id,ours_wins,ga_wins,talkg_wins,instag_wins
1145,A3VQDUUA2RI8KL,176,218,B,q3,0,1,0,0
1146,A3VQDUUA2RI8KL,176,218,B,q1,1,0,0,0
1139,A3VQDUUA2RI8KL,176,104,B,q3,0,0,0,1
1134,A3VQDUUA2RI8KL,176,074,A,q1,1,0,0,0
1140,A3VQDUUA2RI8KL,176,218,A,q1,1,0,0,0
...,...,...,...,...,...,...,...,...,...
1181,AKRPDCCP793ET,1731,304,B,q3,1,0,0,0
1180,AKRPDCCP793ET,1731,304,B,q2,1,0,0,0
1182,AKRPDCCP793ET,1731,306,A,q1,1,0,0,0
1183,AKRPDCCP793ET,1731,306,A,q2,1,0,0,0
1168,AKRPDCCP793ET,1731,218,B,q2,0,0,0,1

In [107]:
df

,WorkerId,WorkTimeInSeconds,subj,speech,q_id,methodA,methodB,methodA_wins,methodB_wins,ours_wins,ga_wins,talkg_wins,instag_wins
0,A1WTHBAWHRVU4P,559,104,B,q1,ours,instag,True,False,1,0,0,0
1,A1WTHBAWHRVU4P,559,104,B,q2,ours,instag,True,False,1,0,0,0
2,A1WTHBAWHRVU4P,559,104,B,q3,ours,instag,True,False,1,0,0,0
3,A1WTHBAWHRVU4P,559,218,A,q1,ours,ga,True,False,1,0,0,0
4,A1WTHBAWHRVU4P,559,218,A,q2,ours,ga,True,False,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3235,A2KWD81ZH7T234,977,306,A,q2,ours,talkg,True,False,1,0,0,0
3236,A2KWD81ZH7T234,977,306,A,q3,ours,talkg,True,False,1,0,0,0
3237,A2KWD81ZH7T234,977,306,B,q1,talkg,ours,False,True,1,0,0,0
3238,A2KWD81ZH7T234,977,306,B,q2,talkg,ours,False,True,1,0,0,0
3239,A2KWD81ZH7T234,977,306,B,q3,talkg,ours,False,True,1,0,0,0

In [ ]:
# count how many times methodA has value 'ga' and methodB has value 'ga'
num_ga = df[(df['methodA'] == 'ga') | (df['methodB'] == 'ga')].shape[0]
num_ga

# 9 subj x 2 speech x 20 responses = 360 (per question)
# 9 subj x 2 speech x 20 responses x 3 questions = 1080 (total answers)

1080